sudo: false
language: node_js
node_js:
  - "14"
branches:
  only:
    - main
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
  - yarn test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
